export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const RESET_ERROR = "RESET_ERROR";
